# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_course_abc_to_mti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseold',
            name='speakers',
        ),
        migrations.AlterModelOptions(
            name='talk',
            options={'verbose_name': 'curso', 'verbose_name_plural': 'cursos'},
        ),
        migrations.DeleteModel(
            name='CourseOld',
        ),
    ]
